### ISSUE TITLE
the exe crashed

### ISSUE THREAD

**Issue by backtoback1** [hlldz/SpookFlare#1]
Hi 
i'm compile the code and run it on windows 8 32bit 
but in the last step when generate the payload it's crashed

**Comment by hlldz** [comment]
Hi,

Could you share the output or screenshot of the crash.

**Comment by backtoback1** [comment]
https://image.prntscr.com/image/g3RrzQ_ASPy6NsExzlAc2g.png

**Comment by backtoback1** [comment]
any help ?

**Comment by hlldz** [comment]
Now I tried again in Windows 7 SP1 32-bit  and Windows 8 32-bit/64-Bit, it worked without any problems.

Can you debug in Visual Studio and share more detailed information?

**Comment by backtoback1** [comment]
https://image.prntscr.com/image/d8MfayJlTKyRtrMP4u_O9A.png

https://image.prntscr.com/image/HeQkaS_KRa_84yye2izfKA.png

note: i have visual studio 2012

**Comment by backtoback1** [comment]
can you give me the compiled one ?

**Comment by backtoback1** [comment]
Hi i fix the problem Thanks

**Comment by hlldz** [comment]
How did you fix the problem? Could it be useful for others, can you share?

**Comment by backtoback1** [comment]
@hlldz just change net framework of project from version 2 to version 4.5

**Comment by hlldz** [comment]
Yes, I forgot to mention that. Thank you.
