### ISSUE TITLE
Run tool

### ISSUE THREAD

**Issue by d0ubl3puls4r** [hlldz/SpookFlare#2]
Hi, I would like to know how to run the tool on the Kali Linux terminal, tried in a few ways but could not execute, tried ./SpookFlare.sln but did not run, what would be the correct procedure?
Thank you.

**Comment by hlldz** [comment]
Hi,

You need to compile the code using Visual Studio. After compiling, you can run SpookFlare in Windows and generate payloads.

This will be helpful, https://msdn.microsoft.com/en-us/library/jj153219.aspx or you can search "how to compile C# code" on the Internet.

Also you can download the compiled version of SpookFlare v1.0 64-Bit, https://github.com/hlldz/SpookFlare/releases/tag/v1.0
