### ISSUE TITLE
using no ip or other dns

### ISSUE THREAD

**Issue by X0R1972** [hlldz/SpookFlare#3]
hi friend
is it possible in place of ip to write my no-ip adress?

**Comment by X0R1972** [comment]
thank you for your answer jerk

**Comment by usama7628674** [comment]
@mateo24xx. You're a piece of junk.If you wanna know just type your no-ip and check yourself out.

**Comment by mateo24xx** [comment]
AND YOU ARE A PIECE OF SHIT..IF YOU DONT WANT PEOPLE ASKING YOU QUESTIONS ABOUT YOUR STUPID TOOL ,WHAT THE FUCK ARE YOU DOING HERE IN GITHUB
DO YOU REALLY THINK THAT I DIDNT TEST IF NO IP WORK YES OR NO..I PUT NO IP ADRESS BUT NOTHING HAPPENDS ???? THATS WHY I ASKED YOU ,,,YOU PIECE OF SHIT
