### ISSUE TITLE
pip installation issue

### ISSUE THREAD

**Issue by usama7628674** [hlldz/SpookFlare#6]
When I run pip install -r requirements.txt in kali linux I get the following.

![image](https://user-images.githubusercontent.com/29252277/39670296-a7a9cc6e-511a-11e8-8680-4204ca66209d.png)

I also got the same error for textwrap

**Comment by hlldz** [comment]
Hi,

I made a mistake and I fixed. Could you clone the project and try again?

**Comment by usama7628674** [comment]
@hlldz Now there is nothing in main menu.
![image](https://user-images.githubusercontent.com/29252277/39671473-6b25e4ea-5132-11e8-8c3a-bb16392279aa.png)

**Comment by usama7628674** [comment]
@hlldz Working fine now.Thanks
