### ISSUE TITLE
File "spookflare.py", line 31

### ISSUE THREAD

**Issue by xajyvi** [hlldz/SpookFlare#7]
I'm having some issues running spookflare in Windows 10. Python is installed and `$ pip install -r requirements.txt` worked without any errors. What am I doing wrong here?

	C:\Users\xajyvi\Desktop\SpookFlare>python spookflare.py
	  File "spookflare.py", line 31
		print " \n\n \033[1m\033[94m[*]\033[0m Exited but do not forget to stay in the shadows!\033[0m\n"
																										^
	SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" \n\n \033[1m\033[94m[*]\033[0m Exited but do not forget to stay in the shadows!\033[0m\n")?

	C:\Users\xajyvi\Desktop\SpookFlare>.\spookflare.py
	  File "C:\Users\xajyvi\Desktop\SpookFlare\spookflare.py", line 31
		print " \n\n \033[1m\033[94m[*]\033[0m Exited but do not forget to stay in the shadows!\033[0m\n"
																										^
	SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" \n\n \033[1m\033[94m[*]\033[0m Exited but do not forget to stay in the shadows!\033[0m\n")?

**Comment by hlldz** [comment]
Which version of Python you are using?

**Comment by xajyvi** [comment]
I installed the [latest version](https://www.python.org/ftp/python/3.6.5/python-3.6.5-amd64.exe) I could find

**Comment by hlldz** [comment]
Could you try this https://www.python.org/downloads/release/python-2714/ for now?

You can use the Python 3 series after pending pull request.

**Comment by cclauss** [comment]
A fix to this issue was merged in #4.
