### ISSUE TITLE
exe has stopped working

### ISSUE THREAD

**Issue by xajyvi** [hlldz/SpookFlare#8]
The target Windows 10 operating system is using x64, also used x64 when generating the EXE. An msf connection is established between my windows device and kali device, but the EXE crashes almost immediately and the connection is closed.

![spook](https://user-images.githubusercontent.com/38975395/39732464-2663b4e6-525d-11e8-8ae1-5f76ecf77438.png)

This time I used the latest available [release](https://github.com/hlldz/SpookFlare/releases/tag/v1.0). But I've noticed the v1.0 interface is a lot different from the latest interface used when I `git clone` your repository. @hlldz

**Comment by hlldz** [comment]
I would recommend using the second version of the first version.

If you are still using the first version, do you use the EnableStageEncoding and StageEncoder values when switching to the listening mode with Metasploit? Also did you patch the Metasploit?

**Comment by xajyvi** [comment]
> "I would recommend using the second version of the first version."

Did you mean [v2.0](https://github.com/hlldz/SpookFlare/releases/)? Sorry, I totally missed that release somehow and used v1.0. I'll try v2.0 and report back tomorrow. Thanks

**Comment by hlldz** [comment]
Is there still a problem?
